name: american-radicalism
favicon: null
layout_spectrum: 0.62103
typography_spectrum: 0.8502406715415418
title: 'American Radicalism: A Project to Restore the Foundations of American Exceptionalism'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eaedfd'
    - '#05040c'
    - '#19628e'
    - '#81479d'
    - '#8691b9'
  brandStrength: 0.8513937289826572
  lightness: 0.604396432172507
  saturation: 0.30255868076346815
  rhythmicContrast: 0.16566993715241551
purpose: []
