name: american-radicalism
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8502406715415418
title: 'American Radicalism: A Project to Restore the Foundations of American Exceptionalism'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8513937289826572
  lightness: 0.604396432172507
  saturation: 0.30255868076346815
  rhythmicContrast: 0.16566993715241551
purpose: []
