name: american-radicalism
favicon: null
layout_spectrum: 0.76461
typography_spectrum: 0.82019
title: 'American Radicalism: A Project to Restore the Foundations of American Exceptionalism'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77658645-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eaedfd'
    - '#05040c'
    - '#19628e'
    - '#81479d'
    - '#8691b9'
  brandStrength: 0.0625
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
