name: american-radicalism
favicon: null
layout_spectrum: 1
typography_spectrum: 0.82019
title: 'American Radicalism: A Project to Restore the Foundations of American Exceptionalism'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eaedfd'
    - '#05040c'
    - '#19628e'
    - '#81479d'
    - '#8691b9'
  brandStrength: 0.625
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
